version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_ADDRESS=redis:6379
      - REQUEST_LIMIT_IP=5
      - BLOCK_TIME_IP=60
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
